server:
    port: 8088  #端口
    servlet-path: /  #拦截路径
logging: #日志级别
    level:
        org:
            springframework: INFO
#自定义属性
girl:
    age: 12
    name: "小明"

spring:
#数据源
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/testspringboot?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
# 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
mvc:
    view:
        prefix: /
        suffix: .jsp   #前后缀
#resources:
#  static-locations: #静态资源路径